networks:
    laravelbackendapi-network:
        driver: bridge

services:
    mysql:
        container_name: "mysql"
        image: mariadb:11.6
        restart: unless-stopped
        volumes:
            - ../laravelbackendapidb/mysql:/var/www/html/laravelbackendapidb
            - ../laravelbackendapidb/mysql:/var/lib/mysql
            - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_TCP_PORT: "${DB_PORT}"
            TZ: "UTC"
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
        ports:
            - "7655:7655"
        networks:
            - laravelbackendapi-network

    laravelbackendapi:
        container_name: "laravelbackendapi"
        build:
            context: .
            dockerfile: ./dockerfiles/swoole.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        depends_on:
            mysql:
                condition: service_started
        environment:
            - DB_DATABASE=laravelapibackend
            - DB_HOST=mysql
            - DB_PORT=7655
            - DB_USERNAME=root
            - DB_PASSWORD=myPassword123
            - CACHE_STORE=redis
            - CACHE_DRIVER=redis
            - CACHE_PREFIX=laravelapibackend_cache_
            - REDIS_DATABASE=0
            - REDIS_CACHE_DB=0
            - REDIS_CLIENT=phpredis
            - REDIS_HOST=redis
            - REDIS_PORT=7656
            - REDIS_USERNAME=default
            - REDIS_PASSWORD=redisPass123
            - MAIL_MAILER=smtp
            - MAIL_SCHEME=null
            - MAIL_BCC=
            - MAIL_HOST=
            - MAIL_PORT=587
            - MAIL_USERNAME=username@host.com
            - MAIL_PASSWORD=password
            - MAIL_ENCRYPTION=tls
            - MAIL_FROM_ADDRESS=
            - ADMIN_EMAIL=
            - MAIL_FROM_NAME="Mail from API"
            - APP_NAME="Laravel Backend API"
            - APP_KEY=base64:6HLMt8Ik9tTwNfudCfN+Z74VFcpjaWTDUc+N3Y1LUW0= # generate a new key with `php artisan key:generate`
            - OCTANE_SERVER=swoole
            - OCTANE_HTTPS=false # change in production to true
        volumes:
            - ./:/var/www/html/src
            - ./dockerfiles/configs/php.ini:/usr/local/etc/php/php.ini
            - ./dockerfiles/configs/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        ports:
            - "7654:7654"
            - "5173:5173"
        networks:
            - laravelbackendapi-network
    redis:
        container_name: "redis"
        image: redis:alpine
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
        ports:
            - "7656:7656"
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./dockerfiles/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            - laravelbackendapi-network
    webserver:
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./public:/var/www/html/src/public:ro
            - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:ro
            - ./ssl:/etc/nginx/ssl:ro
        depends_on:
            - laravelbackendapi
        restart: unless-stopped
        networks:
            - laravelbackendapi-network
